[project]
name = "bayesian-methods"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "plotly>=6.3.0",
    "scipy>=1.13.1",
]
